name: 🔧 Tool Submission Request
description: Request a new tool to be added to the Sunshine-AIO Community Library
title: "[TOOL REQUEST] "
labels: ["tool-request", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🛠️ Tool Submission Request
        
        Thank you for contributing to the Sunshine-AIO Community Library! 
        Please fill out this form to request a new tool to be added to our registry.
        
        **Before submitting:**
        - Search existing tools to avoid duplicates
        - Ensure the tool is open source and actively maintained
        - The tool should have clear documentation and installation instructions

  - type: input
    id: tool-name
    attributes:
      label: Tool Name
      description: The name of the tool (alphanumeric, hyphens, and underscores only)
      placeholder: "my-awesome-tool"
    validations:
      required: true

  - type: textarea
    id: tool-description
    attributes:
      label: Description
      description: Brief description of what this tool does (10-150 characters)
      placeholder: "A powerful CLI tool for automating build processes with Docker support..."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the most appropriate category for this tool
      options:
        - automation/build-tools
        - automation/deployment
        - automation/ci-cd
        - testing/unit-testing
        - testing/integration-testing
        - testing/performance
        - utilities/file-management
        - utilities/system-tools
        - utilities/network
        - development/debugging
        - development/profiling
        - security/scanning
    validations:
      required: true

  - type: input
    id: subcategory
    attributes:
      label: Subcategory (Optional)
      description: More specific classification if needed
      placeholder: "docker-tools"

  - type: input
    id: repository
    attributes:
      label: GitHub Repository
      description: Full GitHub repository URL
      placeholder: "https://github.com/username/repository"
    validations:
      required: true

  - type: input
    id: documentation
    attributes:
      label: Documentation URL (Optional)
      description: Link to documentation (README, wiki, or dedicated docs site)
      placeholder: "https://github.com/username/repository#readme"

  - type: dropdown
    id: license
    attributes:
      label: License
      description: Open source license used by this tool
      options:
        - MIT
        - Apache-2.0
        - GPL-3.0
        - BSD-3-Clause
        - ISC
        - LGPL-3.0
        - MPL-2.0
        - Unlicense
    validations:
      required: true

  - type: checkboxes
    id: platforms
    attributes:
      label: Supported Platforms
      description: Which platforms does this tool support?
      options:
        - label: Windows
        - label: Linux
        - label: macOS
        - label: Web
        - label: Cross-platform

  - type: dropdown
    id: language
    attributes:
      label: Primary Language
      description: Main programming language used
      options:
        - Python
        - JavaScript
        - TypeScript
        - Go
        - Rust
        - Java
        - C++
        - C#
        - PHP
        - Ruby
        - Shell
        - Other

  - type: input
    id: tags
    attributes:
      label: Tags (Optional)
      description: Comma-separated tags for better searchability (lowercase, hyphens only)
      placeholder: "docker, automation, ci-cd, deployment"

  - type: textarea
    id: maintainer-info
    attributes:
      label: Maintainer Information
      description: Information about the tool maintainer
      placeholder: |
        Name: John Doe
        GitHub: johndoe
        Contact: john@example.com (optional)

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional context, features, or notes about this tool
      placeholder: |
        - Key features that make this tool valuable
        - Any special requirements or dependencies
        - Why it should be included in the registry

  - type: checkboxes
    id: quality-checklist
    attributes:
      label: Quality Checklist
      description: Please verify these requirements before submitting
      options:
        - label: The tool is actively maintained (commits within the last year)
          required: true
        - label: The repository has clear documentation (README with installation/usage)
          required: true
        - label: The tool is open source with a compatible license
          required: true
        - label: I have searched existing tools to ensure this is not a duplicate
          required: true
        - label: The repository URL is accessible and correct
          required: true

  - type: checkboxes
    id: contribution-agreement
    attributes:
      label: Contribution Agreement
      description: By submitting this request, you agree to the following
      options:
        - label: I understand that this tool will be reviewed by maintainers
          required: true
        - label: I agree that the tool information may be modified for consistency
          required: true
        - label: I confirm that I have the right to submit this tool for inclusion
          required: true